In [2]:
import numpy as np


###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [12]:
arr = np.random.randint(0,100,12).reshape(3,4)
arr

array([[25, 19,  2, 53],
       [41, 31, 96, 69],
       [13,  5, 25, 61]], dtype=int32)

In [ ]:
# code here
# i. Sort this matrix. np.sort()

np.sort(arr)

array([[23, 37, 52, 67],
       [ 5, 19, 25, 96],
       [ 0, 58, 69, 72]], dtype=int32)

In [ ]:
# ii. Sort this matrix based on values in 2nd column.
sorted_by_2nd_col = arr[arr[:, 1].argsort()]           
sorted_by_2nd_col

array([[37, 23, 67, 52],
       [72, 69,  0, 58],
       [25, 96, 19,  5]], dtype=int32)

In [13]:
sorted_by_row_max = arr[arr.max(axis=1).argsort()]      # iii. sort rows by row-wise max (ascending)
sorted_by_row_max

array([[25, 19,  2, 53],
       [13,  5, 25, 61],
       [41, 31, 96, 69]], dtype=int32)

In [14]:
sorted_elements = np.sort(arr, axis=None).reshape(arr.shape)  # iv. sort all elements and reshape
sorted_elements

array([[ 2,  5, 13, 19],
       [25, 25, 31, 41],
       [53, 61, 69, 96]], dtype=int32)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [15]:
# code here
marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

# i. add extra subject as new column
marks5 = np.column_stack((marks, extra_subject))

# ii. add two new student records (each length 5)
new_students = np.vstack((rec1, rec2))
marks_with_new = np.vstack((marks5, new_students))

# iii. add extra column with total marks (5 subjects)
totals = marks_with_new.sum(axis=1)
marks_with_total = np.column_stack((marks_with_new, totals))

# iv. sort non-ascending on total marks and show top 2 rows
sorted_desc = marks_with_total[marks_with_total[:, -1].argsort()[::-1]]
top2 = sorted_desc[:2]

print("\nQ2 marks_with_total:\n", marks_with_total)
print("Top 2 by total:\n", top2)



Q2 marks_with_total:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
Top 2 by total:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [16]:
# code here
arr3 = np.array([[1,2,3,3,1,1],
                 [0,9,1,2,8,8],
                 [1,2,3,8,8,8],
                 [1,2,3,3,1,1]])
# row-wise unique rows
unique_rows = np.unique(arr3, axis=0)
# col-wise unique columns (unique on transposed, then transpose back)
unique_cols = np.unique(arr3.T, axis=0).T

print("\nQ3 unique_rows:\n", unique_rows)
print("Q3 unique_cols:\n", unique_cols)



Q3 unique_rows:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
Q3 unique_cols:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [17]:
# code here
arr4 = np.arange(12).reshape(3,4)
flipped = arr4[::-1, ::-1]   # or np.flip(arr4)
print("\nQ4 arr4:\n", arr4)
print("flipped both axes:\n", flipped)



Q4 arr4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flipped both axes:
 [[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [18]:
# code here
arr5 = np.array([[1,2,3,4,5],
                 [10,-3,30,4,5],
                 [3,2,5,-4,5],
                 [9,7,3,6,5]])
X = 6
rows_with_gt_X = np.where((arr5 > X).any(axis=1))[0]   # row indices
print("\nQ5 rows_with_gt_X:", rows_with_gt_X)



Q5 rows_with_gt_X: [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [19]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3b = np.arange(7,10)
flat = np.concatenate((arr1, arr2, arr3b))
print("\nQ6 flat:\n", flat)



Q6 flat:
 [0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [20]:
# code here
np.random.seed(400)
arr7 = np.random.randint(100, 1000, 200).reshape((1, 200))
flat7 = arr7.flatten()
idx_min = flat7.argmin()
idx_max = flat7.argmax()
# delete both indices (ensure correct order)
to_delete = sorted({idx_min, idx_max}, reverse=True)
res7 = flat7.copy()
for i in to_delete:
    res7 = np.delete(res7, i)
res7 = res7.reshape(1, -1)
print("\nQ7 original shape:", arr7.shape, "after removal shape:", res7.shape)



Q7 original shape: (1, 200) after removal shape: (1, 198)


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [21]:
# code here
arr8 = np.array([120, 50, 250, 700, 180, 199, 100, 300])
clipped = np.clip(arr8, 100, 200)
sorted_clipped = np.sort(clipped)
cumsum_sorted = np.cumsum(sorted_clipped)
print("\nQ8 clipped:\n", clipped)
print("sorted_clipped:\n", sorted_clipped)
print("cumsum_sorted:\n", cumsum_sorted)


Q8 clipped:
 [120 100 200 200 180 199 100 200]
sorted_clipped:
 [100 100 120 180 199 200 200 200]
cumsum_sorted:
 [ 100  200  320  500  699  899 1099 1299]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [22]:
# code here
rng = np.random.default_rng(0)
arr9 = rng.random(1000)  # example arr in [0,1]
arr9_rounded = np.round(arr9, 3)
p0 = np.percentile(arr9_rounded, 0)
p100 = np.percentile(arr9_rounded, 100)
p50 = np.percentile(arr9_rounded, 50)
p51 = np.percentile(arr9_rounded, 51)
diff_51_50 = p51 - p50
print("\nQ9 p0(min):", p0, "p100(max):", p100, "diff p51-p50:", diff_51_50)


Q9 p0(min): 0.0 p100(max): 1.0 diff p51-p50: 0.013970000000000149
