**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.zeros(10,dtype=int)
a[5]=1
a


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here
print('Enter shapes a,b of which array to be generated')
a = int(input('Enter a:'))
b = int(input('Enter b:'))

arr = np.random.randint(1,100,size=(a, b))

np.mean(arr)

Enter shapes a,b of which array to be generated
Enter a:4
Enter b:5


np.float64(43.85)

4###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
def create_2d_array(a,b):
  x = np.zeros((a,b))
  x[::a-1,:]=1
  x[:,::b-1]=1
  return x


print(create_2d_array(5,10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.random.random(10)

array([0.41209893, 0.04579198, 0.11187621, 0.97282141, 0.70352878,
       0.74365687, 0.44170099, 0.60319089, 0.19608635, 0.32604696])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
# no We can not
# Identity matrix of 4*4
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [4]:
#Code here
np.random.randint(0,4,size=(5,5))

array([[0, 1, 2, 0, 2],
       [3, 1, 3, 0, 1],
       [1, 2, 2, 0, 3],
       [0, 2, 2, 2, 1],
       [2, 3, 0, 1, 2]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
vector = np.random.randint(0,100,size=(10,2))
print(vector)

point = np.array([2,3])

distance = vector-point
print('Diatance from point is :')
print(distance)

[[38 87]
 [92 99]
 [12 90]
 [83  9]
 [90 46]
 [32 57]
 [36  7]
 [13 60]
 [ 9 85]
 [89 97]]
Diatance from point is :
[[36 84]
 [90 96]
 [10 87]
 [81  6]
 [88 43]
 [30 54]
 [34  4]
 [11 57]
 [ 7 82]
 [87 94]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
x = np.arange(6*7*8).reshape(6,7,8)
print(x)
print(np.shape(x))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
x = input('Enter numbers')
list1 = (x.split())



n = np.array(list1,dtype=float)
print(n[::-1])


Enter numbers1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
x = np.array([1,2,3,4,5,6])
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Elements_count :',x.size)

Elements_count : 9


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
l1 = [86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318]
x = np.array(l1)
y = np.exp(x)/sum(np.exp(x))
print(y)

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
# Remaining

def Stcking(arr1,arr2):
  x = np.vstack((arr1,arr2))
  return x

a = np.arange(10).reshape(2,5)
b = np.ones((2,5))
print(a)
print(b)

Stcking(a,b)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
# def create_Random_dates(sdate,edate):
#   s = np.array(sdate.split('-'))
#   e = np.array(edate.split('-'))

#   print(s)
#   print(e)



# sdate = input('Enter starting date.')
# edate = input('Enter Ending date.')
# create_Random_dates(sdate,edate)

# copied
import numpy as np
from datetime import datetime

def date_array(start, end):
    # Validate exactly 2 string arguments
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both arguments must be strings.")

    # Validate date format
    date_format = "%Y-%m-%d"
    try:
        start_date = datetime.strptime(start, date_format)
        end_date   = datetime.strptime(end, date_format)
    except ValueError:
        raise ValueError("Date format must be 'YYYY-MM-DD', e.g. '2022-12-6'.")

    # Validate start is before end
    if start_date > end_date:
        raise ValueError("Start date must be before or equal to end date.")

    # Generate date range (inclusive of end)
    dates = np.arange(start, end, dtype="datetime64[D]")
    dates = np.append(dates, np.datetime64(end, "D"))  # include end date

    return dates.astype(str)


# Example
print(date_array(start="2020-09-15", end="2020-09-25"))




['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
x = np.arange(50).reshape(10,5)

print(x)
print('After subtracting mean:')
for i in range(10):
   m = np.mean(x[i,:])
   y = x[i,:]-m
   print(y)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
After subtracting mean:
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]
[-2. -1.  0.  1.  2.]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
x = np.arange(10).reshape(5,2)
print(x)
x[:,[0,1]] = x[:,[1,0]]

x

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
a = np.arange(10).reshape(5,2)
a
a[a %2==0] = -1
a

array([[-1,  1],
       [-1,  3],
       [-1,  5],
       [-1,  7],
       [-1,  9]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
l = []
for i in range(0,len(a)):
    if a[i]>b[i]:
      l.append(a[i])
    else:
      l.append(b[i])
print(l)

# import numpy as np

a = np.array([1, 5, 3, 9, 2])
b = np.array([4, 2, 7, 1, 8])

result = np.maximum(a, b)
print(result)  # [4 5 7 9 8]


[np.int64(6), np.int64(3), np.int64(1), np.int64(7), np.int64(8)]
[4 5 7 9 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
x=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
x

array([[1857, 5162, 1220, 7765, 2442],
       [6990, 1304, 4174, 9939, 2022],
       [4555, 8048, 9550, 9796, 4155],
       [9208, 7232, 1765, 5842,  740],
       [7528, 6245, 9404, 6966, 7708],
       [6483, 9969,  293, 4171,  614],
       [5940, 6538, 1434, 4637, 4127],
       [5958, 2979, 6695, 6303, 9138]])

In [ ]:
#Code here
y = (x-np.min(x))/(np.max(x)-np.min(x))
y

array([[0.11111111, 0.        ],
       [0.33333333, 0.22222222],
       [0.55555556, 0.44444444],
       [0.77777778, 0.66666667],
       [1.        , 0.88888889]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def nth_largest(arr,n):
  if n>len(arr):
    print('Error.')
  else:
    arr.sort()
    print(arr[-n])

arr = np.array([2,4,5,8,3,4,0])
nth_largest(arr,2)

5


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
a[0]

np.int64(1)

In [ ]:
# copied
import numpy as np

a = np.array([1, 2, 3])

result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(result)  # [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
