In [1]:
import numpy as np

## 0D Tensor(Scalar)

In [2]:
a = np.array(4)

In [3]:
a

array(4)

In [4]:
a.ndim

0

## 1D Tensor(Vector)

In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [7]:
a.ndim

1

## 2D Tensor(Matrix)

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.ndim

2

## ND Tensor

In [17]:
# 3D Tensor
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])

In [16]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [18]:
# 4D Tensor
np.array([
    [[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]],
    [[[10,20,30],[40,50,60],[70,80,90]],[[100,200,300],[400,500,600],[700,800,900]]]
    ])

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  20,  30],
         [ 40,  50,  60],
         [ 70,  80,  90]]],


       [[[ 10,  20,  30],
         [ 40,  50,  60],
         [ 70,  80,  90]],

        [[100, 200, 300],
         [400, 500, 600],
         [700, 800, 900]]]])

## Rank,Axis and Shape

- No. of Axis = Rank = No. of Dimensions

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# No. of Axis = 2(row,column)
# Shape = 3,3
# size = 3*3 = 9 (m*n)