### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types





### Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Create Numpy Arrays

In [4]:
# np.array
import numpy as np

# 1D
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# 2D 3D

b = np.array([[1,2,3],[4,5,6]])
print(b)

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# dtype

print(np.array([1,2,3],dtype = float))
print(np.array([1,2,3],dtype = bool))
print(np.array([1,2,3],dtype = complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [13]:
# np.arrange

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# with reshape()
a.reshape(2,5)
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
# np.ones and np.zeros

print(np.ones((3,3)))
print(np.zeros((2,2)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [42]:
# np.random
print(np.random.random((3,4)))

[[0.30622983 0.14484989 0.8374618  0.58911082]
 [0.89687865 0.04586008 0.12170382 0.97336407]
 [0.99502725 0.96082931 0.41500922 0.23896365]]


In [34]:
# np.linspace (lower range,upper range, how many numbers)
np.linspace(1,100,10,dtype = int)
# generates points at equal distrance


array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [26]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [60]:
a1 = np.arange(10,dtype =np.int16)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
a2 = np.arange(12,dtype = float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [48]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [53]:
# ndim
a1.ndim
a2.ndim
a3.ndim

3

In [55]:
# shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [57]:
# size
a1.size
a2.size
a3.size


8

In [61]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

2
8
8


In [62]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int16
float64
int64


#### Changing Dataypes

In [65]:
# astype
a3.dtype
a3.astype(np.int16)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

### Array Operations

In [68]:
a1 = np.arange(12).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [69]:
a2 = np.arange(12,24).reshape(3,4)
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [76]:
# Scalar Operation

# arithmatic
a1+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [71]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [75]:
# Relational
a2 > 15
a1 > 10
a1 == 10


array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [78]:
# Vector Operations
a1 + a2
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

### Array Functions


In [80]:
a1 = np.random.random((3,3))*100
a1 = np.round(a1)
print(a1)

[[ 9. 79. 65.]
 [77.  3. 26.]
 [76. 59. 93.]]


In [85]:
# max/min/sum/product

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

np.max(a1,axis=1)# 1->Row,0->Column
np.prod(a1,axis=1)


93.0
3.0
487.0
115748890737480.0


array([ 46215.,   6006., 417012.])

In [86]:
# mean/median/std/var

print(np.mean(a1))
print(np.median(a1,axis=1))
print(np.std(a1))
print(np.var(a1))


54.111111111111114
[65. 26. 76.]
31.117856411621947
968.320987654321


In [88]:
# Trignomatric Function
print(np.sin(a1))


[[ 0.41211849 -0.44411267  0.82682868]
 [ 0.99952016  0.14112001  0.76255845]
 [ 0.56610764  0.63673801 -0.94828214]]


In [89]:
# Dot product (n*m m*o -> possible)

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [91]:
# log and Exponents
np.log(a1)
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [96]:
# round/floor/ceil

x = np.random.random((2,3))*100
print(x)
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))

[[12.64829173 65.69346746  4.11431708]
 [92.25772759 13.96838089 73.55807692]]
[[13. 66.  4.]
 [92. 14. 74.]]
[[12. 65.  4.]
 [92. 13. 73.]]
[[13. 66.  5.]
 [93. 14. 74.]]


### Indexing and Slicing

In [116]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [117]:
# 1D
a1[0]

np.int64(0)

In [104]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [109]:
# 2D

# 6
a2[1][2]
# 11
a2[2][3]

np.float64(11.0)

In [107]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [113]:
# 3D
# 5
a3[1][0][1]
# 3
a3[0][1][1]
# 0
a3[0][0][0]
# 6
a3[1][1][0]

np.int64(6)

In [118]:
# Slicing

# 1D

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a1[2:5]

array([2, 3, 4])

In [123]:
# 2D
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [124]:
a2[0,:]
a2[:,2]

array([ 2.,  6., 10.])

In [125]:
# 5 6 9 10
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [126]:
# 0 3 8 11 
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [129]:
# 1 3 9 11
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [130]:
# 4 7
a2[1,::3]

array([4., 7.])

In [131]:
# 1 2 3
# 5 6 7
a2[0:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [132]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [134]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [135]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [137]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
# 3 4 5 
a3 [0,1,:]

array([3, 4, 5])

In [140]:
# 10 13 16
a3 [1,:,1]

array([10, 13, 16])

In [141]:
# 22 23
# 25 26

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [142]:
# 0 2 
# 18 20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [144]:
print(a1)
for i in a1:
    print(i)



[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [146]:
print(a2)
for i in a2:
    print(i)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [148]:
print(a3)
for i in a3:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [149]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [152]:
# reshape
a1 = a1.reshape(2,5)

In [154]:
# transpose
np.transpose(a1)
a1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [156]:
# reval(convert nD array to 1D)
a1.ravel()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Stacking

In [162]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))
np.hstack((a4,a5,a4))

# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###  Spliting

In [169]:
np.hsplit(a4,4)


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [167]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]