In [2]:
import numpy as np
import random

### np.sort
Return a sorted copy of an array.

In [5]:
a = np.random.randint(1,100,15)
print(a)
a = np.sort(a)
a
np.sort(a)[::-1]

[46 88 75 57 77 57 97 29 53 47 88 16 22 52  3]


array([97, 88, 88, 77, 75, 57, 57, 53, 52, 47, 46, 29, 22, 16,  3],
      dtype=int32)

In [11]:
b = np.random.randint(1,20,20).reshape(4,5)
print(b)
s = np.sort(b) #default -> row wise(1)
print(s)

y = np.sort(b,axis = 0) # column wise
print(y)

[[16  1 17 13 19]
 [16  1  6  8 19]
 [ 5 16  1  6  2]
 [ 6 15 11 12  5]]
[[ 1 13 16 17 19]
 [ 1  6  8 16 19]
 [ 1  2  5  6 16]
 [ 5  6 11 12 15]]
[[ 5  1  1  6  2]
 [ 6  1  6  8  5]
 [16 15 11 12 19]
 [16 16 17 13 19]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [21]:
np.append(a,200)


array([  1,  19,  47,  49,  49,  51,  52,  62,  64,  75,  76,  84,  92,
        96,  97, 200])

In [22]:
b

array([[13,  1, 17, 16,  3],
       [13,  7, 10,  6,  7],
       [10,  3,  5, 14,  8],
       [13, 15, 17,  4,  5]], dtype=int32)

In [24]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[13.,  1., 17., 16.,  3.,  1.],
       [13.,  7., 10.,  6.,  7.,  1.],
       [10.,  3.,  5., 14.,  8.,  1.],
       [13., 15., 17.,  4.,  5.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [25]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [30]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [31]:
e = np.array([1,1,1,2,2,4,5,4,6,])
np.unique(e)

array([1, 2, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [32]:
a.shape

(15,)

In [33]:
np.expand_dims(a,axis = 0).shape

(1, 15)

np.expand_dims(a,axis = 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [36]:
a

array([ 1, 19, 47, 49, 49, 51, 52, 62, 64, 75, 76, 84, 92, 96, 97],
      dtype=int32)

In [38]:
np.where(a>50) # gives index positions of given condition


(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [39]:
# replace all values >50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 1, 19, 47, 49, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [40]:
np.argmax(a)

np.int64(14)

In [41]:
b

array([[13,  1, 17, 16,  3],
       [13,  7, 10,  6,  7],
       [10,  3,  5, 14,  8],
       [13, 15, 17,  4,  5]], dtype=int32)

In [42]:
np.argmax(b,axis=0)

array([0, 3, 0, 0, 2])

In [43]:
# np.argmin
np.argmin(a)

np.int64(0)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.


In [44]:
a 

array([ 1, 19, 47, 49, 49, 51, 52, 62, 64, 75, 76, 84, 92, 96, 97],
      dtype=int32)

In [45]:
np.cumsum(a)

array([  1,  20,  67, 116, 165, 216, 268, 330, 394, 469, 545, 629, 721,
       817, 914])

In [47]:
b
# np.cumsum(b,axis=0)

array([[13,  1, 17, 16,  3],
       [13,  7, 10,  6,  7],
       [10,  3,  5, 14,  8],
       [13, 15, 17,  4,  5]], dtype=int32)

In [49]:
np.cumsum(b,axis=0)

array([[13,  1, 17, 16,  3],
       [26,  8, 27, 22, 10],
       [36, 11, 32, 36, 18],
       [49, 26, 49, 40, 23]])

In [50]:
# np.cumprod
np.cumprod(a)

array([                   1,                   19,                  893,
                      43757,              2144093,            109348743,
                 5686134636,         352540347432,       22562582235648,
           1692193667673600,   128606718743193600, -7643779699281289216,
       -2251457532915646464,  5221005724612558848,  8375465297260314624])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

In [51]:
a

array([ 1, 19, 47, 49, 49, 51, 52, 62, 64, 75, 76, 84, 92, 96, 97],
      dtype=int32)

In [54]:
np.percentile(a,100)

np.float64(97.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [55]:
a

array([ 1, 19, 47, 49, 49, 51, 52, 62, 64, 75, 76, 84, 92, 96, 97],
      dtype=int32)

In [57]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 0, 0, 3, 2, 2, 2, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

In [3]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [6]:
a

array([ 3, 16, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

In [7]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.


In [8]:
a

array([ 3, 16, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

In [9]:
np.flip(a)

array([97, 88, 88, 77, 75, 57, 57, 53, 52, 47, 46, 29, 22, 16,  3],
      dtype=int32)

In [12]:
b

array([[16,  1, 17, 13, 19],
       [16,  1,  6,  8, 19],
       [ 5, 16,  1,  6,  2],
       [ 6, 15, 11, 12,  5]], dtype=int32)

In [13]:
np.flip(b)

array([[ 5, 12, 11, 15,  6],
       [ 2,  6,  1, 16,  5],
       [19,  8,  6,  1, 16],
       [19, 13, 17,  1, 16]], dtype=int32)

In [14]:
np.flip(b,axis = 0)

array([[ 6, 15, 11, 12,  5],
       [ 5, 16,  1,  6,  2],
       [16,  1,  6,  8, 19],
       [16,  1, 17, 13, 19]], dtype=int32)

In [15]:
np.flip(b,axis = 1)

array([[19, 13, 17,  1, 16],
       [19,  8,  6,  1, 16],
       [ 2,  6,  1, 16,  5],
       [ 5, 12, 11, 15,  6]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

In [16]:
a

array([ 3, 16, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

In [18]:
np.put(a,[0,1],[10,20])

In [19]:
a

array([10, 20, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

In [20]:
a

array([10, 20, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

In [22]:
np.delete(a,[0,1])

array([22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97], dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [25]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
np.intersect1d(m,n)

array([3, 4, 5])

In [28]:
np.setdiff1d(m,n)

array([1, 2])

In [30]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [31]:
m[np.in1d(m,1)]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7376\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.


In [32]:
a

array([10, 20, 22, 29, 46, 47, 52, 53, 57, 57, 75, 77, 88, 88, 97],
      dtype=int32)

In [33]:
np.clip(a,a_min = 25,a_max=75)

array([25, 25, 25, 29, 46, 47, 52, 53, 57, 57, 75, 75, 75, 75, 75],
      dtype=int32)

In [34]:
# 17. np.swapaxes

In [35]:
# 18. np.uniform

In [36]:
# 19. np.count_nonzero

In [37]:
# 21. np.tile

In [38]:
# 22. np.repeat

In [39]:
# 25. np.allclose and equals